// Mock data for the Champions League dashboard
import type { Match, MatchDetails } from "@/lib/types"

// Sample match data
const mockMatches: Match[] = [
  {
    id: "1",
    homeTeam: "Barcelona",
    awayTeam: "Bayern Munich",
    score: "2 - 1",
    status: "FINISHED",
    timestamp: 1713294000, // April 16, 2025, 19:00 UTC
  },
  {
    id: "2",
    homeTeam: "Real Madrid",
    awayTeam: "Manchester City",
    score: "1 - 1",
    status: "FINISHED",
    timestamp: 1713380400, // April 17, 2025, 19:00 UTC
  },
  {
    id: "3",
    homeTeam: "PSG",
    awayTeam: "Liverpool",
    score: "0 - 0",
    status: "SCHEDULED",
    timestamp: 1713553200, // April 19, 2025, 19:00 UTC
  },
  {
    id: "4",
    homeTeam: "Juventus",
    awayTeam: "Chelsea",
    score: "0 - 0",
    status: "SCHEDULED",
    timestamp: 1713639600, // April 20, 2025, 19:00 UTC
  },
]

// Mock match details
const mockMatchDetails: Record<string, MatchDetails> = {
  "1": {
    incidents: [
      {
        minute: 23,
        type: "GOAL",
        playerName: "Robert Lewandowski",
        teamName: "Barcelona",
        assistedBy: "Pedri",
      },
      {
        minute: 45,
        type: "YELLOW_CARD",
        playerName: "Joshua Kimmich",
        teamName: "Bayern Munich",
      },
      {
        minute: 67,
        type: "GOAL",
        playerName: "Jamal Musiala",
        teamName: "Bayern Munich",
      },
      {
        minute: 89,
        type: "GOAL",
        playerName: "Lamine Yamal",
        teamName: "Barcelona",
      },
    ],
    stats: {
      home: {
        possessionPercent: 58,
        shots: {
          total: 15,
          onTarget: 7,
          offTarget: 8,
        },
        passes: {
          total: 578,
          accurate: 512,
        },
        corners: 8,
        fouls: 10,
        offsides: 2,
      },
      away: {
        possessionPercent: 42,
        shots: {
          total: 10,
          onTarget: 4,
          offTarget: 6,
        },
        passes: {
          total: 423,
          accurate: 356,
        },
        corners: 5,
        fouls: 12,
        offsides: 3,
      },
    },
    lineups: {
      home: {
        teamName: "Barcelona",
        formation: "4-3-3",
        players: [
          {
            id: "h1",
            name: "Marc-André ter Stegen",
            number: 1,
            position: "GK",
            role: "STARTER",
            rating: 7.8,
            teamName: "Barcelona",
            stats: {
              saves: 3,
              conceded: 1,
            },
          },
          {
            id: "h2",
            name: "Jules Koundé",
            number: 2,
            position: "RB",
            role: "STARTER",
            rating: 7.2,
            teamName: "Barcelona",
            stats: {
              tackles: 4,
              interceptions: 2,
            },
          },
          {
            id: "h3",
            name: "Ronald Araújo",
            number: 4,
            position: "CB",
            role: "STARTER",
            rating: 7.5,
            teamName: "Barcelona",
            stats: {
              clearances: 6,
              blocks: 2,
            },
          },
          {
            id: "h4",
            name: "Iñigo Martínez",
            number: 5,
            position: "CB",
            role: "STARTER",
            rating: 7.3,
            teamName: "Barcelona",
            stats: {
              clearances: 5,
              interceptions: 3,
            },
          },
          {
            id: "h5",
            name: "Alejandro Balde",
            number: 3,
            position: "LB",
            role: "STARTER",
            rating: 7.0,
            teamName: "Barcelona",
            stats: {
              tackles: 3,
              assists: 0,
            },
          },
          {
            id: "h6",
            name: "Pedri",
            number: 8,
            position: "CM",
            role: "STARTER",
            rating: 8.2,
            teamName: "Barcelona",
            stats: {
              assists: 1,
              passes: 78,
              shots: 2,
            },
          },
          {
            id: "h7",
            name: "Frenkie de Jong",
            number: 21,
            position: "CM",
            role: "STARTER",
            rating: 7.8,
            teamName: "Barcelona",
            stats: {
              passes: 92,
              interceptions: 4,
            },
          },
          {
            id: "h8",
            name: "Ilkay Gündogan",
            number: 22,
            position: "CM",
            role: "STARTER",
            rating: 7.6,
            teamName: "Barcelona",
            stats: {
              passes: 85,
              shots: 3,
            },
          },
          {
            id: "h9",
            name: "Lamine Yamal",
            number: 27,
            position: "RW",
            role: "STARTER",
            rating: 8.5,
            teamName: "Barcelona",
            stats: {
              goals: 1,
              assists: 0,
              shots: 4,
            },
          },
          {
            id: "h10",
            name: "Robert Lewandowski",
            number: 9,
            position: "ST",
            role: "STARTER",
            rating: 8.3,
            teamName: "Barcelona",
            stats: {
              goals: 1,
              shots: 5,
            },
          },
          {
            id: "h11",
            name: "Raphinha",
            number: 11,
            position: "LW",
            role: "STARTER",
            rating: 7.4,
            teamName: "Barcelona",
            stats: {
              shots: 3,
              assists: 0,
            },
          },
          {
            id: "h12",
            name: "Fermín López",
            number: 16,
            position: "CM",
            role: "SUBSTITUTE",
            rating: 6.8,
            teamName: "Barcelona",
            stats: {},
          },
          {
            id: "h13",
            name: "Ferran Torres",
            number: 7,
            position: "FW",
            role: "SUBSTITUTE",
            rating: 6.5,
            teamName: "Barcelona",
            stats: {},
          },
        ],
      },
      away: {
        teamName: "Bayern Munich",
        formation: "4-2-3-1",
        players: [
          {
            id: "a1",
            name: "Manuel Neuer",
            number: 1,
            position: "GK",
            role: "STARTER",
            rating: 7.0,
            teamName: "Bayern Munich",
            stats: {
              saves: 5,
              conceded: 2,
            },
          },
          {
            id: "a2",
            name: "Noussair Mazraoui",
            number: 40,
            position: "RB",
            role: "STARTER",
            rating: 6.8,
            teamName: "Bayern Munich",
            stats: {
              tackles: 3,
              interceptions: 1,
            },
          },
          {
            id: "a3",
            name: "Dayot Upamecano",
            number: 2,
            position: "CB",
            role: "STARTER",
            rating: 7.1,
            teamName: "Bayern Munich",
            stats: {
              clearances: 7,
              blocks: 1,
            },
          },
          {
            id: "a4",
            name: "Kim Min-jae",
            number: 3,
            position: "CB",
            role: "STARTER",
            rating: 7.0,
            teamName: "Bayern Munich",
            stats: {
              clearances: 6,
              interceptions: 2,
            },
          },
          {
            id: "a5",
            name: "Alphonso Davies",
            number: 19,
            position: "LB",
            role: "STARTER",
            rating: 7.4,
            teamName: "Bayern Munich",
            stats: {
              tackles: 4,
              assists: 0,
            },
          },
          {
            id: "a6",
            name: "Joshua Kimmich",
            number: 6,
            position: "CDM",
            role: "STARTER",
            rating: 7.2,
            teamName: "Bayern Munich",
            stats: {
              passes: 76,
              yellowCards: 1,
            },
          },
          {
            id: "a7",
            name: "Leon Goretzka",
            number: 8,
            position: "CDM",
            role: "STARTER",
            rating: 6.9,
            teamName: "Bayern Munich",
            stats: {
              passes: 65,
              interceptions: 3,
            },
          },
          {
            id: "a8",
            name: "Leroy Sané",
            number: 10,
            position: "RW",
            role: "STARTER",
            rating: 7.3,
            teamName: "Bayern Munich",
            stats: {
              shots: 2,
              assists: 1,
            },
          },
          {
            id: "a9",
            name: "Jamal Musiala",
            number: 42,
            position: "CAM",
            role: "STARTER",
            rating: 8.0,
            teamName: "Bayern Munich",
            stats: {
              goals: 1,
              shots: 3,
              passes: 45,
            },
          },
          {
            id: "a10",
            name: "Kingsley Coman",
            number: 11,
            position: "LW",
            role: "STARTER",
            rating: 7.1,
            teamName: "Bayern Munich",
            stats: {
              shots: 2,
              assists: 0,
            },
          },
          {
            id: "a11",
            name: "Harry Kane",
            number: 9,
            position: "ST",
            role: "STARTER",
            rating: 7.5,
            teamName: "Bayern Munich",
            stats: {
              shots: 4,
              assists: 0,
            },
          },
          {
            id: "a12",
            name: "Thomas Müller",
            number: 25,
            position: "FW",
            role: "SUBSTITUTE",
            rating: 6.7,
            teamName: "Bayern Munich",
            stats: {},
          },
          {
            id: "a13",
            name: "Serge Gnabry",
            number: 7,
            position: "FW",
            role: "SUBSTITUTE",
            rating: 6.5,
            teamName: "Bayern Munich",
            stats: {},
          },
        ],
      },
    },
  },
  "2": {
    incidents: [
      {
        minute: 34,
        type: "GOAL",
        playerName: "Vinícius Júnior",
        teamName: "Real Madrid",
      },
      {
        minute: 72,
        type: "GOAL",
        playerName: "Kevin De Bruyne",
        teamName: "Manchester City",
        assistedBy: "Phil Foden",
      },
      {
        minute: 78,
        type: "YELLOW_CARD",
        playerName: "Rodri",
        teamName: "Manchester City",
      },
    ],
    stats: {
      home: {
        possessionPercent: 45,
        shots: {
          total: 12,
          onTarget: 5,
          offTarget: 7,
        },
        passes: {
          total: 489,
          accurate: 423,
        },
        corners: 6,
        fouls: 14,
        offsides: 1,
      },
      away: {
        possessionPercent: 55,
        shots: {
          total: 16,
          onTarget: 6,
          offTarget: 10,
        },
        passes: {
          total: 612,
          accurate: 567,
        },
        corners: 9,
        fouls: 8,
        offsides: 2,
      },
    },
    lineups: {
      home: {
        teamName: "Real Madrid",
        formation: "4-3-3",
        players: [
          {
            id: "h1",
            name: "Thibaut Courtois",
            number: 1,
            position: "GK",
            role: "STARTER",
            rating: 7.6,
            teamName: "Real Madrid",
            stats: {
              saves: 5,
              conceded: 1,
            },
          },
          {
            id: "h2",
            name: "Dani Carvajal",
            number: 2,
            position: "RB",
            role: "STARTER",
            rating: 7.2,
            teamName: "Real Madrid",
            stats: {
              tackles: 5,
              interceptions: 2,
            },
          },
          {
            id: "h3",
            name: "Antonio Rüdiger",
            number: 22,
            position: "CB",
            role: "STARTER",
            rating: 7.5,
            teamName: "Real Madrid",
            stats: {
              clearances: 8,
              blocks: 3,
            },
          },
          {
            id: "h4",
            name: "Éder Militão",
            number: 3,
            position: "CB",
            role: "STARTER",
            rating: 7.3,
            teamName: "Real Madrid",
            stats: {
              clearances: 6,
              interceptions: 4,
            },
          },
          {
            id: "h5",
            name: "Ferland Mendy",
            number: 23,
            position: "LB",
            role: "STARTER",
            rating: 7.0,
            teamName: "Real Madrid",
            stats: {
              tackles: 4,
              assists: 0,
            },
          },
          {
            id: "h6",
            name: "Federico Valverde",
            number: 15,
            position: "CM",
            role: "STARTER",
            rating: 7.8,
            teamName: "Real Madrid",
            stats: {
              passes: 68,
              shots: 2,
            },
          },
          {
            id: "h7",
            name: "Aurélien Tchouaméni",
            number: 18,
            position: "CDM",
            role: "STARTER",
            rating: 7.4,
            teamName: "Real Madrid",
            stats: {
              passes: 75,
              interceptions: 5,
            },
          },
          {
            id: "h8",
            name: "Toni Kroos",
            number: 8,
            position: "CM",
            role: "STARTER",
            rating: 8.1,
            teamName: "Real Madrid",
            stats: {
              passes: 92,
              assists: 1,
            },
          },
          {
            id: "h9",
            name: "Rodrygo",
            number: 11,
            position: "RW",
            role: "STARTER",
            rating: 7.3,
            teamName: "Real Madrid",
            stats: {
              shots: 3,
              assists: 0,
            },
          },
          {
            id: "h10",
            name: "Jude Bellingham",
            number: 5,
            position: "CAM",
            role: "STARTER",
            rating: 7.9,
            teamName: "Real Madrid",
            stats: {
              shots: 4,
              passes: 65,
            },
          },
          {
            id: "h11",
            name: "Vinícius Júnior",
            number: 7,
            position: "LW",
            role: "STARTER",
            rating: 8.4,
            teamName: "Real Madrid",
            stats: {
              goals: 1,
              shots: 5,
            },
          },
          {
            id: "h12",
            name: "Luka Modrić",
            number: 10,
            position: "CM",
            role: "SUBSTITUTE",
            rating: 7.0,
            teamName: "Real Madrid",
            stats: {},
          },
          {
            id: "h13",
            name: "Eduardo Camavinga",
            number: 12,
            position: "CM",
            role: "SUBSTITUTE",
            rating: 6.8,
            teamName: "Real Madrid",
            stats: {},
          },
        ],
      },
      away: {
        teamName: "Manchester City",
        formation: "4-3-3",
        players: [
          {
            id: "a1",
            name: "Ederson",
            number: 31,
            position: "GK",
            role: "STARTER",
            rating: 7.2,
            teamName: "Manchester City",
            stats: {
              saves: 4,
              conceded: 1,
            },
          },
          {
            id: "a2",
            name: "Kyle Walker",
            number: 2,
            position: "RB",
            role: "STARTER",
            rating: 7.3,
            teamName: "Manchester City",
            stats: {
              tackles: 3,
              interceptions: 2,
            },
          },
          {
            id: "a3",
            name: "Rúben Dias",
            number: 3,
            position: "CB",
            role: "STARTER",
            rating: 7.5,
            teamName: "Manchester City",
            stats: {
              clearances: 5,
              blocks: 2,
            },
          },
          {
            id: "a4",
            name: "John Stones",
            number: 5,
            position: "CB",
            role: "STARTER",
            rating: 7.4,
            teamName: "Manchester City",
            stats: {
              clearances: 4,
              interceptions: 3,
            },
          },
          {
            id: "a5",
            name: "Joško Gvardiol",
            number: 24,
            position: "LB",
            role: "STARTER",
            rating: 7.1,
            teamName: "Manchester City",
            stats: {
              tackles: 4,
              assists: 0,
            },
          },
          {
            id: "a6",
            name: "Rodri",
            number: 16,
            position: "CDM",
            role: "STARTER",
            rating: 7.7,
            teamName: "Manchester City",
            stats: {
              passes: 89,
              yellowCards: 1,
            },
          },
          {
            id: "a7",
            name: "Bernardo Silva",
            number: 20,
            position: "CM",
            role: "STARTER",
            rating: 7.6,
            teamName: "Manchester City",
            stats: {
              passes: 78,
              shots: 2,
            },
          },
          {
            id: "a8",
            name: "Kevin De Bruyne",
            number: 17,
            position: "CM",
            role: "STARTER",
            rating: 8.3,
            teamName: "Manchester City",
            stats: {
              goals: 1,
              passes: 72,
              shots: 4,
            },
          },
          {
            id: "a9",
            name: "Phil Foden",
            number: 47,
            position: "RW",
            role: "STARTER",
            rating: 8.0,
            teamName: "Manchester City",
            stats: {
              assists: 1,
              shots: 3,
            },
          },
          {
            id: "a10",
            name: "Erling Haaland",
            number: 9,
            position: "ST",
            role: "STARTER",
            rating: 7.4,
            teamName: "Manchester City",
            stats: {
              shots: 5,
              assists: 0,
            },
          },
          {
            id: "a11",
            name: "Jack Grealish",
            number: 10,
            position: "LW",
            role: "STARTER",
            rating: 7.2,
            teamName: "Manchester City",
            stats: {
              shots: 2,
              assists: 0,
            },
          },
          {
            id: "a12",
            name: "Jérémy Doku",
            number: 11,
            position: "FW",
            role: "SUBSTITUTE",
            rating: 6.8,
            teamName: "Manchester City",
            stats: {},
          },
          {
            id: "a13",
            name: "Mateo Kovačić",
            number: 8,
            position: "CM",
            role: "SUBSTITUTE",
            rating: 6.7,
            teamName: "Manchester City",
            stats: {},
          },
        ],
      },
    },
  },
  "3": {
    incidents: [],
    stats: {
      home: {
        possessionPercent: 0,
        shots: {
          total: 0,
          onTarget: 0,
          offTarget: 0,
        },
        passes: {
          total: 0,
          accurate: 0,
        },
        corners: 0,
        fouls: 0,
        offsides: 0,
      },
      away: {
        possessionPercent: 0,
        shots: {
          total: 0,
          onTarget: 0,
          offTarget: 0,
        },
        passes: {
          total: 0,
          accurate: 0,
        },
        corners: 0,
        fouls: 0,
        offsides: 0,
      },
    },
    lineups: {
      home: {
        teamName: "PSG",
        formation: "4-3-3",
        players: [
          {
            id: "h1",
            name: "Gianluigi Donnarumma",
            number: 1,
            position: "GK",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h2",
            name: "Achraf Hakimi",
            number: 2,
            position: "RB",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h3",
            name: "Marquinhos",
            number: 5,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h4",
            name: "Lucas Hernández",
            number: 21,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h5",
            name: "Nuno Mendes",
            number: 25,
            position: "LB",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h6",
            name: "Vitinha",
            number: 17,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h7",
            name: "Warren Zaïre-Emery",
            number: 33,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h8",
            name: "Fabián Ruiz",
            number: 8,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h9",
            name: "Ousmane Dembélé",
            number: 10,
            position: "RW",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h10",
            name: "Kylian Mbappé",
            number: 7,
            position: "ST",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h11",
            name: "Bradley Barcola",
            number: 29,
            position: "LW",
            role: "STARTER",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h12",
            name: "Marco Asensio",
            number: 11,
            position: "FW",
            role: "SUBSTITUTE",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
          {
            id: "h13",
            name: "Lee Kang-in",
            number: 19,
            position: "MF",
            role: "SUBSTITUTE",
            rating: 0,
            teamName: "PSG",
            stats: {},
          },
        ],
      },
      away: {
        teamName: "Liverpool",
        formation: "4-3-3",
        players: [
          {
            id: "a1",
            name: "Alisson",
            number: 1,
            position: "GK",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a2",
            name: "Trent Alexander-Arnold",
            number: 66,
            position: "RB",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a3",
            name: "Ibrahima Konaté",
            number: 5,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a4",
            name: "Virgil van Dijk",
            number: 4,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a5",
            name: "Andy Robertson",
            number: 26,
            position: "LB",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a6",
            name: "Alexis Mac Allister",
            number: 10,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a7",
            name: "Dominik Szoboszlai",
            number: 8,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a8",
            name: "Curtis Jones",
            number: 17,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a9",
            name: "Mohamed Salah",
            number: 11,
            position: "RW",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a10",
            name: "Darwin Núñez",
            number: 9,
            position: "ST",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a11",
            name: "Luis Díaz",
            number: 7,
            position: "LW",
            role: "STARTER",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a12",
            name: "Cody Gakpo",
            number: 18,
            position: "FW",
            role: "SUBSTITUTE",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
          {
            id: "a13",
            name: "Harvey Elliott",
            number: 19,
            position: "MF",
            role: "SUBSTITUTE",
            rating: 0,
            teamName: "Liverpool",
            stats: {},
          },
        ],
      },
    },
  },
  "4": {
    incidents: [],
    stats: {
      home: {
        possessionPercent: 0,
        shots: {
          total: 0,
          onTarget: 0,
          offTarget: 0,
        },
        passes: {
          total: 0,
          accurate: 0,
        },
        corners: 0,
        fouls: 0,
        offsides: 0,
      },
      away: {
        possessionPercent: 0,
        shots: {
          total: 0,
          onTarget: 0,
          offTarget: 0,
        },
        passes: {
          total: 0,
          accurate: 0,
        },
        corners: 0,
        fouls: 0,
        offsides: 0,
      },
    },
    lineups: {
      home: {
        teamName: "Juventus",
        formation: "3-5-2",
        players: [
          {
            id: "h1",
            name: "Wojciech Szczęsny",
            number: 1,
            position: "GK",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h2",
            name: "Federico Gatti",
            number: 4,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h3",
            name: "Bremer",
            number: 3,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h4",
            name: "Danilo",
            number: 6,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h5",
            name: "Andrea Cambiaso",
            number: 27,
            position: "RWB",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h6",
            name: "Manuel Locatelli",
            number: 5,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h7",
            name: "Adrien Rabiot",
            number: 25,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h8",
            name: "Weston McKennie",
            number: 16,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h9",
            name: "Samuel Iling-Junior",
            number: 17,
            position: "LWB",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h10",
            name: "Dušan Vlahović",
            number: 9,
            position: "ST",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h11",
            name: "Federico Chiesa",
            number: 7,
            position: "ST",
            role: "STARTER",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h12",
            name: "Arkadiusz Milik",
            number: 14,
            position: "ST",
            role: "SUBSTITUTE",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
          {
            id: "h13",
            name: "Nicolò Fagioli",
            number: 21,
            position: "CM",
            role: "SUBSTITUTE",
            rating: 0,
            teamName: "Juventus",
            stats: {},
          },
        ],
      },
      away: {
        teamName: "Chelsea",
        formation: "4-2-3-1",
        players: [
          {
            id: "a1",
            name: "Robert Sánchez",
            number: 1,
            position: "GK",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a2",
            name: "Reece James",
            number: 24,
            position: "RB",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a3",
            name: "Wesley Fofana",
            number: 33,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a4",
            name: "Thiago Silva",
            number: 6,
            position: "CB",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a5",
            name: "Marc Cucurella",
            number: 3,
            position: "LB",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a6",
            name: "Enzo Fernández",
            number: 8,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a7",
            name: "Moisés Caicedo",
            number: 25,
            position: "CM",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a8",
            name: "Cole Palmer",
            number: 20,
            position: "RW",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a9",
            name: "Conor Gallagher",
            number: 23,
            position: "CAM",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a10",
            name: "Mykhailo Mudryk",
            number: 10,
            position: "LW",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a11",
            name: "Nicolas Jackson",
            number: 15,
            position: "ST",
            role: "STARTER",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a12",
            name: "Christopher Nkunku",
            number: 18,
            position: "FW",
            role: "SUBSTITUTE",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
          {
            id: "a13",
            name: "Noni Madueke",
            number: 11,
            position: "FW",
            role: "SUBSTITUTE",
            rating: 0,
            teamName: "Chelsea",
            stats: {},
          },
        ],
      },
    },
  },
}

// API functions
export async function fetchMatches(): Promise<Match[]> {
  // Simulate API call
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockMatches)
    }, 500)
  })
}

export async function fetchMatchById(id: string): Promise<Match | null> {
  // Simulate API call
  return new Promise((resolve) => {
    setTimeout(() => {
      const match = mockMatches.find((m) => m.id === id)
      resolve(match || null)
    }, 300)
  })
}

export async function fetchMatchDetails(id: string): Promise<MatchDetails> {
  // Simulate API call
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const details = mockMatchDetails[id]
      if (details) {
        resolve(details)
      } else {
        reject(new Error(`Match details not found for ID: ${id}`))
      }
    }, 800)
  })
}
